version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
    env_file:
      - web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
  api:
    depends_on:
      - postgres_db
    ports:
      - 8080:8080
    build:
      context: ./api
      dockerfile: Dockerfile
  postgres_db:
    image: postgres 
    restart: always
    env_file:
      - web/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data: