# Generated by Django 4.2.11 on 2024-03-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
